<?php
/**
 * @file
 * The primary PHP file for the Uikitty base theme.
 *
 */

/**
 * Implements hook_theme_suggestions_page_alter().
 */
 
function uikitty_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  // Add content type suggestions.
  if ($node = \Drupal::request()->attributes->get('node')) {
    array_splice($suggestions, 1, 0, 'page__node__' . $node->getType());
  }
}